name: encode

# 触发条件
on:
  workflow_dispatch:
  # 定时触发
  schedule:
    # 每12小时获取一次
    - cron: '0 */12 * * *'

env:
  UPLOAD_CONFIG: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3     #git clone
      with: { ref: rename }
    - uses: actions/setup-python@v4 #python环境
      with:
        python-version: '3.x'       #python 3.x
        cache: 'pip'                #pip cache
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装pip包
      run: | 
         pip install -r ./requirements.txt
    - name: 执行任务
      run: |
         rm ./output || ls
         #wget ${{ secrets.Check_File }} -O ./nodeencode -q
         #base64 ./nodelist > nodeencode -w 0
         #wget ${{ secrets.Check_File2 }} -O ./nodeencode2 -q
         wget -q https://raw.githubusercontent.com/vpei/Free-Node-Merge/main/res/nod-0.txt -O ./nodeencode1
         #wget -q https://raw.githubusercontent.com/vpei/Free-Node-Merge/main/res/nod-1.txt -O ./nodeencode3
         wget -q https://raw.githubusercontent.com/vpei/Free-Node-Merge/main/o/node.txt -O ./nodeencode4
         wget -q https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/all -O ./nodeencode5
         wget -q https://github.com/tindy2013/subconverter/releases/download/v0.7.2/subconverter_linux32.tar.gz && tar -zxvf subconverter_linux32.tar.gz >/dev/null && rm ./subconverter_linux32.tar.gz
         rm ./Country.mmdb || ls
         wget https://github.com/Dreamacro/maxmind-geoip/raw/release/Country.mmdb -O ./Country.mmdb -q
         wget ${{ secrets.Check_File3 }} -O ./sub/sub_list.json -q
         python ./sub/list_merge.py && mv ./sub/sub_merge_base64.txt ./nodeencode0
         #mv ./nodeencode ./subconverter
         mv ./nodeencode1 ./subconverter
         #mv ./nodeencode2 ./subconverter
         #mv ./nodeencode3 ./subconverter
         mv ./nodeencode4 ./subconverter
         mv ./nodeencode5 ./subconverter
         mv ./nodeencode0 ./subconverter
         cp -rf ./generate.ini ./subconverter && cp ./node_profile.ini ./subconverter && cp ./example_external_config.ini ./subconverter && ./subconverter/subconverter -g --artifact "node" && iconv -f UTF-8 -t UTF-8 -c ./subconverter/input.yaml -o ./input.yaml && rm ./subconverter/input.yaml
         echo "Compile_Date=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
         sed -i 's/!<str> //g' ./input.yaml && python main.py
    - name: 上传文件在 github actions
      uses: actions/upload-artifact@v3
      if: env.UPLOAD_CONFIG == 'true'
      with:
        name: .yaml_${{ env.Compile_Date }}
        path: ./output.yaml
    - name: 执行任务2    
      run:  |                      
         rm ./input.yaml
         #cp ./check_profile.ini ./subconverter && mv ./output.yaml ./subconverter && ./subconverter/subconverter -g --artifact "check" && iconv -f UTF-8 -t UTF-8 -c ./subconverter/input.yaml -o ./clashcheck/data/input.yaml && rm ./subconverter/input.yaml
         mv ./output.yaml ./clashcheck/data/input.yaml      
         cp -rf ./Country.mmdb ./clashcheck && cd ./clashcheck && chmod 777 ./clash-linux-amd64 && python main.py
         rm ./data/input.yaml
         rm -rf ./__pycache__
         cd .. && mv ./clashcheck/data/check.yaml ./subconverter/output.yaml && ./subconverter/subconverter -g --artifact "base64" && mv ./subconverter/output ./       
         rm -rf ./subconverter
         rm -rf ./__pycache__
    - name: 提交更改
      run: |
         git config core.ignorecase false
         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"
         git add .
         git commit -m "$(date '+%Y-%m-%d %H:%M:%S')更新"
         git pull origin rename
         git push origin rename
